version: 0.2

phases:
  pre_build:
    commands:
      - echo "登录 Amazon ECR..."
      - echo "aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin xxxx.dkr.ecr.ap-northeast-1.amazonaws.com"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - echo "cd ./service"
      - echo "docker build -t xxx/backend:latest ."
      - echo "docker tag xxx/backend:latest xxxx.dkr.ecr.ap-northeast-1.amazonaws.com/xxx/service:latest"   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo docker push xxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/xxx/service:latest
      - echo cd ..
      - echo printf '[{"name":"service","imageUri":"xxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/xxx/service:latest"}]' > imagedefinitions.json
artifacts:
  files: 
   - ./service/imagedefinitions.json
   - '**/*'
  name: BuildService
